name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: crazy-max/ghaction-github-contribution-grid-snake@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-snake.svg

      - name: Push the generated snake
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-snake.svg
